### ISSUE TITLE
External data sources

### ISSUE THREAD

**Issue by hardbyte** [hardbyte/netchecks#33]
Currently config and secrets get hard coded into the networkassertion resource e.g:

```yaml
apiVersion: netchecks.io/v1
kind: NetworkAssertion
metadata:
  name: http-header-example
  namespace: default
  annotations:
    description: Assert header returned from pie.dev service
spec:
  schedule: "*/10 * * * *"
  rules:
    - name: pie-dev-headers-and-validation
      type: http
      url: https://pie.dev/headers
      headers:
        "X-Netcheck-Header": "some-secret"
```

This ticket is to design and implement a method for using data from K8s ConfigMaps and Secrets. Initially I'm thinking of adding a context similar to [Kyverno](https://kyverno.io/docs/writing-policies/external-data-sources/). Say the data is in a config map:

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: some-config-map
  namespace: some-namespace
data:
  API_TOKEN: some-secret
```

The context will be declared in the spec of a NetworkAssertion:

```yaml
spec:
  schedule: "*/10 * * * *"
  context:
    - name: dictionary
      configMap:
        name: some-config-map
        namespace: some-namespace
```

The context can then be used in any individual NetworkAssertion rule:

```yaml
- name: kubernetes-list-policy-reports
  type: http
  url: https://kubernetes/apis/wgpolicyk8s.io/v1alpha2/policyreports?limit=5
  verify-tls-cert: false
  headers:
    - name: Authorization
      value: "Bearer {{dictionary.API_TOKEN}}"
```

This copies kyverno's approach using JMESPath notation, although we might prefer to use CEL. Often the data in the configmap/secret will be JSON or yaml and will need parsing. With CEL that looks something like this:

```
value: "Bearer {{ parse_json(dictionary.json_config).headers['X-Header'] }}"
```

It would be good to consider loading from other sources too - external api calls, mounted files etc but that doesn't need to be implemented in the first version.

### Templating

JINJA would be an easy development choice as the probe is currently written in Python, but we already use CEL for validation rules, and perhaps want to stay closer to other k8s templating systems such as helm which uses [Go template](https://pkg.go.dev/text/template) - see https://pypi.org/project/go-template/

### Template Expression

Kyverno uses the format `{{ "<name>".data."<key>" }}`. Considering dropping the `.data` part.

### Data Access Scope

Where to access the resources and replace the templates with the actual values? In the operator or the probe?

**Operator**
The operator replacing the templated variables seems straight forward, by granting additional permissions to the operator we can access ConfigMaps and Secrets across the cluster then inject the data into the probe via the current method. 

However this goes against the principal of least privilege - it would be better if only the probe had access to the required data/secrets.

Further, some data that might be required for a network check is mounted at runtime by a service account - e.g. AWS tokens.

**Probe**
The job spec currently mounts a `netcheck-rules` volume at `/netcheck` in the probe which contains the contents of a `ConfigMap` specifying what the probe should do (as `rules.json`).

To support external data, each resource in the NetworkAssertion context gets added to the job spec to mount as an additional volume - e.g. the below `some-config-map` context might get mounted `/netcheck/acontext`.

```yaml
  context:
    - name: acontext
      configMap:
        name: some-config-map
        namespace: some-namespace
```

Each entry in the ConfigMap would be projected to an individual file available inside the probe. Using `items` only the required data needs to be made available:

```yaml
  context:
    - name: dictionary
      configMap:
        name: some-config-map
        items:
        - key: some-config-map-entry-name.json
          path: keys.json
```
In this case the data from `some-config-map-entry-name.json` in the configmap gets mounted at ` /netcheck/dictionary/keys.json`.

The probe would then have to be told how to find and interpret these files and replace the variables. Likely we will need to limit support to a few filetypes such as: raw values, json and yaml.

Finding the files is mostly straightforward, along with the `assertions` in the json config file we can pass in a list of `contexts`:

```json
"contexts": [
  {"name": "dictionary", "path": "/netcheck/dictionary/keys.json", "type": "file"},
  {"name": "acontext", "path": "/netcheck/dictionary", "type": "directory"}
]
```

As each item in the config map is projected to its own file, the probe will have to locate the file based on the name from the template. E.g. `"Bearer {{ parse_json(acontext['config.json'])['SECRET-API-KEY'] }}"` will cause the probe to load `/netcheck/dictionary/config.json`, parse it as json, and load the `SECRET-API-KEY` value.

**Comment by hardbyte** [comment]
Test network assertion:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: some-config-map
data:
  API_TOKEN: some-secret
---
apiVersion: netchecks.io/v1
kind: NetworkAssertion
metadata:
  name: http-with-external-data
  namespace: default
  annotations:
    description: Assert probe can access configmap data
spec:
  context:
    - name: somecontext
      configMap:
        name: some-config-map
  rules:
    - name: pie-dev-headers-and-validation
      type: http
      url: https://pie.dev/headers
      headers:
        "X-Netcheck-Header": "secret"
        "X-Netcheck-Configmap": "{{ context.API_TOKEN }}"
      expected: pass
      validate:
        message: Http request with header to pie.dev service should reply with header value
        pattern: "parse_json(data.body).headers['X-Netcheck-Header'] == 'secret'"

```
